# Generated by Django 4.2 on 2024-10-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='name',
            field=models.CharField(default='Unnamed Project', max_length=255),
        ),
    ]
