# Generated by Django 4.2 on 2024-10-05 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
