# Generated by Django 4.2 on 2024-10-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_alter_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
